### ISSUE TITLE
please investigate why these straightforward commands take many hours?  on both unix and windows..thanks!

### ISSUE THREAD

**Issue by ajdamico** [MonetDB/eanthony#11]
```
> dom.design <- svydesign(weight = ~dom_wgt, nest = TRUE, 
+     strata = ~v0011, id = ~v0300, fpc = ~dom_fpc, data = "c10_dom", 
+     dbtype = "Mone ..." ... [TRUNCATED] 
```

**QQ: 'select v0300,v0011,dom_fpc,dom_wgt from c10_dom'**

```
> save(dom.design, file = "dom 2010 design.rda")

> pes.design <- svydesign(weight = ~pes_wgt, nest = TRUE, 
+     strata = ~v0011, id = ~v0300, fpc = ~dom_fpc, data = "c10", 
+     dbtype = "MonetDBL ..." ... [TRUNCATED] 
```

**QQ: 'select v0300,v0011,dom_fpc,pes_wgt from c10'**

source  http://monetdb.cwi.nl/testweb/web/eanthony/fedora20-3/1450966565/censolite.log

**Comment by ajdamico** [comment]
http://monetdb.cwi.nl/testweb/web/eanthony/fedora20-3/1450966565/censolite.log

**Comment by ajdamico** [comment]
censo demografico gets a lot of hits through a link from the brazilian census bureau, so i'd rather not switch the monetdb.r script (master branch) over to the monetdblite (censolite branch) until this is resolved..  thanks holmes

http://www.ibge.gov.br/home/estatistica/populacao/censo2010/default_resultados_amostra.shtm

**Comment by hannesmuehleisen** [comment]
yes something going wrong there. Will check.

**Comment by hannesmuehleisen** [comment]
I did try those queries, they complete within seconds. I think its not the query but the subsequent processing in R that takes forever...

**Comment by hannes** [comment]
I did try those queries, they complete within seconds. I think its not the query but the subsequent processing in R that takes forever. Will add a debug output to MonetDBLite when query finishes so you believe me.

**Comment by ajdamico** [comment]
@hannesmuehleisen hi, no need, i believe you-- pulling twenty million records from four columns into RAM should not take twelve hours, so please resolve whatever's behind that delay..  thanks

**Comment by hannes** [comment]
suggest switching back to sqlsurvey. the time is burnt in the survey package.

**Comment by hannes** [comment]
Working version here: https://github.com/hannesmuehleisen/asdfree/tree/master/Censo%20Demografico

**Comment by ajdamico** [comment]
i don't want to support `sqlsurvey` anymore, but i'll explore this a bit more..

**Comment by ajdamico** [comment]
hi, sorry, i agree that the `select cols1-4` is almost instantaneous.  i still want to dump `sqlsurvey` and have added two timers here https://github.com/MonetDB/eanthony/commit/21a8fbab68e05dee5b70540df5800c313c201dcd to make sure that only the download script takes a long time
