### ISSUE TITLE
all scripts should work comfortably on a 32GB RAM

### ISSUE THREAD

**Issue by ajdamico** [MonetDB/eanthony#14]
the acs 2014 5-year file uses 8.5GB of ram in a fresh R console.  the error `2016-02-04 14:15:52 Error: cannot allocate vector of size 9.3 Gb` on the 32GB lab07win server makes me think we are making a memory allocation mistake somewhere.

this failure makes me think the sequential-testing method running on lab07win is pretty smart.  32GB is much closer to our average user's experience than the 254GB fedora20 monster, and leaving that sequential testing indefinitely might be a good strategy?

does it make sense to add (or partition off a small slice from fedora20) a second 32GB sequential unix test box?  this setup would allow us to distinguish _resource usage errors_ from _windows-specific errors_
1. fedora all-at-once for immediate, fast testing of everything
2. lab07win for sequential windows testing within reasonable memory constraints
3. new_unix_32gb_ram for sequential unix testing within reasonable memory constraints

the two sequential machines would look much closer to the hardware that users have access to

---

more notes about the ram overloading error above--

so in base R, using gc() is not really necessary because the system will figure that out itself when one object needs RAM -- it pushes aside other objects if they have been removed.  i've read that gc() is never really necessary.

a similar thing probably happens within mserver -- if there are limited resources, one command will capture memory that is no longer in use but might have been released

is it possible that the acs and censo crashes are happening because mserver and base R are not capturing unused RAM from one another?

is there a gc() equivalent in mserver?  can we run both gc()-for-R and also gc()-for-mserver in front of every dbSendQuery?

**Comment by hannes** [comment]
R on windows by default limits the memory to the physical amount of memory in the system. If you read a huge table into R, both MonetDB and R needs this table in memory for the transformation. R on windows supports settting a higher `memory.limit()` which I have done for now.

**Comment by ajdamico** [comment]
good to know.  8.5 x 2 is still well below 32gb

**Comment by ajdamico** [comment]
figuring this out might be tough -- certainly possible it's my fault in how i've written the asdfree scripts.

this code worked:

```
setwd("S:/temp/BSAPUF")

library(MonetDB.R)
library(MonetDBLite)
library(downloader)
options(scipen=10)


source_url( 
    "https://raw.githubusercontent.com/ajdamico/asdfree/master/Download%20Cache/download%20cache.R" , 
    prompt = FALSE , 
    echo = FALSE 
)

tf <- tempfile()
download_cached( "http://downloads.cms.gov/BSAPUF/2008_BSA_PartD_Events_PUF_1.zip" , tf , mode = 'wb' )
z <- unzip( tf , exdir = tempdir() )

# simple monetdb setup
db <- dbConnect( MonetDBLite() , getwd() )

# load a simple data file into the database
monet.read.csv( db , z , 'large_table0' )

# stack the table on top of itself into new tables..
# over and over and over again..
# until you start paging.
# on a 64GB windows machine, stacking 6x starts paging
for ( i in 1:6 ){

    print( i )

    print( dbGetQuery( db , paste0( "SELECT COUNT(*) FROM large_table" , i - 1 ) ) )

    dbSendQuery( db , paste0( 'CREATE TABLE large_table' , i , " AS ( SELECT * FROM large_table" , i - 1 , " ) UNION ALL ( SELECT * FROM large_table" , i - 1 , " )" ) )

}

# read the largest table into RAM
x <- dbReadTable( db , 'large_table6' )
# WORKS
```
