### ISSUE TITLE
wilburcam broken on firefox on windows

### ISSUE THREAD

**Issue by ajdamico** [MonetDB/eanthony#19]
shows a black screen in chrome as well, but that might just be because it's nighttime?  should be a quack fix

**Comment by hannes** [comment]
Fixed

**Comment by ajdamico** [comment]
on par with the iss feed

**Comment by ajdamico** [comment]
broken again :(

**Comment by hannes** [comment]
What the quack? But added auto-restarting script for streaming server.

**Comment by ajdamico** [comment]
need a wilbur fix (double-meaning!)

**Comment by hannes** [comment]
Planned power outage on Dijksgracht

**Comment by ajdamico** [comment]
willlllsonnnnn i mean bur - down again :(

**Comment by hannes** [comment]
up again!

**Comment by ajdamico** [comment]
aww yiss

**Comment by ajdamico** [comment]
:(

**Comment by hannes** [comment]
wilbur is free now hence no more wilburcam
