### ISSUE TITLE
include MonetDBLite vignette written in Rmarkdown

### ISSUE THREAD

**Issue by ajdamico** [MonetDB/eanthony#24]
to be mentioned in `on.load`

**Comment by ajdamico** [comment]
@hannesmuehleisen i gotta do this i gotta do this http://blog.revolutionanalytics.com/2016/05/good-r-packages.html

**Comment by ajdamico** [comment]
at the same time, revise or remove the instructions in this folder
https://github.com/ajdamico/asdfree/tree/master/MonetDB

**Comment by ajdamico** [comment]
structure so it's linkable from asdfree (describe why as well as how)

**Comment by ajdamico** [comment]
yeah its tricky. perhaps we can have some basic sql examples? create table, selection, projection, aggregation, joins and refer to larger tutorials?

**Comment by ajdamico** [comment]
not on.load but maybe if user types 'library(MonetDBLite)'

http://stackoverflow.com/questions/37495068/best-practices-to-alert-users-of-package-vignettes-when-librarypackagename-i

**Comment by hannes** [comment]
i like the onAttach solution too

**Comment by ajdamico** [comment]
but only if it's not attached just as a dependency..?

**Comment by ajdamico** [comment]
here's my solution around this block of lines..

https://github.com/Rdatatable/data.table/blob/d9cf539b0fda2197b3a1d3bd5a0b5180b036200f/R/onAttach.R#L16-L20

```
# only print the package startup messages if the user explicitly typed `library(data.table)` or `require(data.table)`
# do not print when the library was loaded as a dependency
if( substitute( library(data.table) ) == sys.calls()[[1]] | substitute( require(data.table) ) == sys.calls()[[1]] ){

    [[startup messages here]]

}
```

**Comment by hannes** [comment]
nice if hacky

**Comment by ajdamico** [comment]
this person thinks it won't work?  @hannesmuehleisen what do you think?

http://stackoverflow.com/questions/37495068/best-practices-to-alert-users-of-package-vignettes-when-librarypackagename-i/37495204?noredirect=1#comment62683142_37495204

**Comment by ajdamico** [comment]
could be a readmette (a readme vignette, pronounced readme yet?)

**Comment by ajdamico** [comment]
intro vignette: six most common commands:

dbConnect
dbWriteTable
  either from data.frame or csv
dbGetQuery
dbSendQuery

dbReadTable
dbDisconnect( ...,shutdown=TRUE)

**Comment by ajdamico** [comment]
https://github.com/hannesmuehleisen/MonetDBLite/pull/54/
