### ISSUE TITLE
submit a patch for MonetDBLite that logs queries to external file

### ISSUE THREAD

**Issue by ajdamico** [MonetDB/eanthony#26]
purpose in mind: when i have a crazy R script that does 1,000 sql commands one after the other, having the sql commands written to a log will make it a lot easier to make a reproducible example when the error can be reproduced with zero-record data tables

```
options( "monetdb.log.query" = "C:/path/to/file.txt" )
```

dbSendQuery is probably the place to do this. Beware there are two, one for normal MonetDB and one for MonetDBLite

**Comment by ajdamico** [comment]
e-mailed patch with

```
if( !is.null( log_file <- getOption( "monetdb.log.query" , NULL ) ) ) cat( statement , file = log_file , sep = "\n" , append = TRUE )
```

**Comment by hannes** [comment]
added to 1.0.1 and uploaded

**Comment by ajdamico** [comment]
thanks
