### ISSUE TITLE
test why `ncvs` crashes on unix

### ISSUE THREAD

**Issue by ajdamico** [MonetDB/eanthony#29]
http://monetdb.cwi.nl/testweb/web/eanthony/fedora20-3/1457251145/ncvs.log
http://monetdb.cwi.nl/testweb/web/eanthony/fedora20-3/1457251145/swmap_ces.log

**Comment by ajdamico** [comment]
further-along ncvs crash on windows
http://monetdb.cwi.nl/testweb/web/eanthony/lab07win/1457012057/ncvs.log

**Comment by ajdamico** [comment]
@hannesmuehleisen please grab latest code from eanthony

after these commits, ncvs now works all the way through on rocks040--
https://github.com/MonetDB/eanthony/commit/ef2fd8c1ca5d951b081b08a756cda65c49bd41ef
https://github.com/ajdamico/asdfree/commit/bdb2c6f696086f75377d353fea6d7070b4c89f7a
https://github.com/ajdamico/asdfree/commit/17b3c06100ed9437b119f47e4965583c8735b3ba

**Comment by hannes** [comment]
updated

**Comment by hannes** [comment]
will try to automate this...

**Comment by ajdamico** [comment]
thanks..  if at the same time it's easy for you to rig lab07win to always pull the latest script, that might be worth it since the cycle is so slow that at the point that it tests, i don't even remember the version/state when the cycle started

**Comment by ajdamico** [comment]
first fedora green
