### ISSUE TITLE
flip SEER to lite then add to eanthony

### ISSUE THREAD

**Issue by ajdamico** [MonetDB/eanthony#32]
http://seer.cancer.gov/seerstat/autoupdate.html

**Comment by ajdamico** [comment]
I apologize for any inconvenience this causes, but we will be releasing a new version of SEER*Stat (8.3.2) on 4/14/16 on port 2038. There is a minor issue in version 8.3.1 that was released on 3/31/16. The only issue is that some rate and prevalence sessions will fail to complete; no incorrect statistics are produced.

Because the issue is minor we will still release 8.3.1 on port 2039 on 4/14/16 as originally planned.  Therefore, people who have already updated to version 8.3.1 can switch to port 2039 on 4/14 and will have about two weeks to review and update to version 8.3.2, when port 2039 will be updated (5/2/16).

Please see this web page for more details: http://seer.cancer.gov/seerstat/autoupdate.html and do not hesitate to email seerstat@imsweb.com any questions you may have.

If you have a problem with the auto-update in SEER_Stat, please try right-clicking on the SEER_Stat icon (desktop or start-menu) and select the option to Run as administrator. Then proceed with the auto-update. This solution works for most people. If that does not work, we have some other options in this FAQ: http://seer.cancer.gov/seerstat/faq.html#install1.

A mailing list is available to sign up for e-mail updates about upcoming SEER*Stat releases. Please visit this web page for more information: http://seer.cancer.gov/seerstat/listserv.html.

The SEER Program is happy to announce the 1973-2013 SEER Research Incidence data (November 2015 submission) will be available on Friday, April 15, 2016.

**Comment by ajdamico** [comment]
The SEER Program is happy to announce the 1973-2013 SEER Research Incidence data (November 2015 submission) is now available.

**Comment by ajdamico** [comment]
hannes, please load the latest eanthony repo..  seer is live now

**Comment by hannes** [comment]
done cool
