### ISSUE TITLE
unexpected pnad crash

### ISSUE THREAD

**Issue by ajdamico** [MonetDB/eanthony#33]
could you delete this file to see if that's the problem?  thanks

```
'/data24r3/hannes/eanthony/r-tmp/4f5bb5be71c9cbdf8f0e66ce03705aa9.Rdownloadercache'
```

**Comment by ajdamico** [comment]
on lab07win, pnad is breaking in a different place -- but please run these four lines on lab07win just to prevent this issue from occurring there as well.. thanks

```
library(downloader)
source_url( "https://raw.githubusercontent.com/ajdamico/asdfree/master/Download%20Cache/download%20cache.R" , prompt = FALSE , echo = FALSE )
tf <- tempfile()
download_cached( 'ftp://ftp.ibge.gov.br/Trabalho_e_Rendimento/Pesquisa_Nacional_por_Amostra_de_Domicilios_anual/microdados/2013/Dicionarios_e_input_20150814.zip' , tf , mode = 'wb' , savecache = TRUE , usecache = FALSE )
```

**Comment by hannes** [comment]
deleted the file on both boxes but would the download not happen anyways?

**Comment by ajdamico** [comment]
thanks.  i am confused about what's breaking here because it works fine for me..  deleting them is the easiest fix so let's try..
