### ISSUE TITLE
unexpected uspums crash

### ISSUE THREAD

**Issue by ajdamico** [MonetDB/eanthony#34]
i believe that my commit will resolve this crash -- https://github.com/ajdamico/asdfree/commit/d5a218999618c82b5cdf7fb0e2692d05352f53da -- but

please delete on fedora20:

```
'/data24r3/hannes/eanthony/r-tmp/dc0563385395c1962bc6b4882777d4cc.Rdownloadercache'
```

please delete on lab07win:

```
'D:/eanthony/r-tmp/dc0563385395c1962bc6b4882777d4cc.Rdownloadercache'
```

thanks

**Comment by hannes** [comment]
done
