### ISSUE TITLE
fix introduced filepath/directory issues on windows

### ISSUE THREAD

**Issue by ajdamico** [MonetDB/eanthony#35]
hannes, i know you're waiting for a verdict on this one, but does it make sense to simply include a `monetizePath` function in `MonetDBLite`?  i think if we replace all `normalizePath` with `monetizePath` then the problem gets solved?

```
monetizePath <- function( filepath ) gsub( "\\\\" , "/" , normalizePath( filepath ) )
```

**Comment by hannes** [comment]
fixed
