### ISSUE TITLE
win-3 cache deletions please

### ISSUE THREAD

**Issue by ajdamico** [MonetDB/eanthony#49]
'G:\eanthony\r-tmp\acs2\RtmpEjxdlY\file26407f6e4733'
'G:\eanthony\r-tmp\acs2\RtmpEjxdlY\file26407f6e4733'

**Comment by hannes** [comment]
those are not cache files and will get deleted automatically

**Comment by ajdamico** [comment]
please delete
'G:/eanthony/r-tmp/acs2/0c19194c9ef943df04d135c65e1574c0.Rdownloadercache'
'G:/eanthony/r-tmp/acs2/d5e6b5103787fbb757255ce387c5c806.Rdownloadercache'
'G:/eanthony/r-tmp/acs2/3518e66dbec91f5817da88963312b2c5.Rdownloadercache'

**Comment by ajdamico** [comment]
also

'G:/eanthony/r-tmp/nvss/0f5ad4f3935bbde366b1c1c51c656f51.Rdownloadercache'
'G:/eanthony/r-tmp/nvss/53d6288213716e06be2eb52f3d8227a5.Rdownloadercache'
'G:/eanthony/r-tmp/nvss/2e29fcdc0331ef32a04501cbb315a8bd.Rdownloadercache'
'G:/eanthony/r-tmp/sipp/a63b38b147df735844bd3468571bcdee.Rdownloadercache'

**Comment by hannes** [comment]
deleted

**Comment by ajdamico** [comment]
```
'G:/eanthony/r-tmp/nvss/21a0e27a4e18bcae131705b9eef7cac1.Rdownloadercache'
'G:/eanthony/r-tmp/nvss/e0e93d382da0ed85804eb8c5a37703c8.Rdownloadercache'
'G:/eanthony/r-tmp/nvss/19123c4a3e99683f8bff755b527f5219.Rdownloadercache'
```

**Comment by ajdamico** [comment]
```
'G:/eanthony/r-tmp/acs/f43ea49f7f78147dbe2394a30b782871.Rdownloadercache'
'G:/eanthony/r-tmp/nibrs/fd29eb9e67ac708058230c0b584f08b6.Rdownloadercache'
'G:/eanthony/r-tmp/ncvs/91a6d63699da20c87f1b5121785e2855.Rdownloadercache'
'G:/eanthony/r-tmp/sbo/1ff53d9735ed4f7c7fdbaf0254353223.Rdownloadercache'
```

**Comment by ajdamico** [comment]
```
'G:/eanthony/r-tmp/sipp/68f897f00a14310ae8fdd0a7e082e255.Rdownloadercache'
```

**Comment by hannes** [comment]
morning

**Comment by ajdamico** [comment]
haha

**Comment by hannes** [comment]
![img_2438](https://cloud.githubusercontent.com/assets/227792/16106394/534a2880-3394-11e6-9613-a7a416cfd0d4.JPG)

**Comment by hannes** [comment]
will move to new windows server today if time permits

**Comment by ajdamico** [comment]
SUP, HIS WILBURNESS?

**Comment by ajdamico** [comment]
@hannesmuehleisen cache deletion please

```
'E:/eanthony/r-tmp/sipp/697f42dec1ede9aee98be3b01278f57b.Rdownloadercache'
```
