### ISSUE TITLE
speed-test.R -- please review & push to live site if you're OK with it?

### ISSUE THREAD

**Issue by ajdamico** [MonetDB/eanthony#52]
it runs through pretty quickly and never uses more than 10GB of RAM on its current max setting of 100,000,000 records.

i had originally thought it would make a good vignette for `MonetDBLite` -- but it would jam up travis, i'm sure.  if you have any ideas how to make the results more readable/useful to users, i can try to revise?  thanks

https://github.com/MonetDB/eanthony/commit/ed3d7cfd82855dfa32e6c0ac4370f47e23f5f740

**Comment by hannes** [comment]
updated nice
