### ISSUE TITLE
fix a couple typos

### ISSUE THREAD

**Issue by ajdamico** [MonetDB/eanthony#54]
https://github.com/MonetDB/eanthony/commit/5948f87177a90545a784ddde56993fa0400c304d

**Comment by ajdamico** [comment]
@hannesmuehleisen please load latest?  this should fix crashes in sipp, pnad, and swmap_pnad

https://github.com/MonetDB/eanthony/commit/4d87631297ac6674e6960625b1b71b36ea7fc78b
https://github.com/MonetDB/eanthony/commit/35b2c71322e7a94ee350ef80e276714c64d2a7ed

**Comment by hannes** [comment]
wilbur says quack

**Comment by ajdamico** [comment]
hahahaha

**Comment by hannes** [comment]
ok should all be set again removed the crashy run. its my fault for not checking those tiny differences.
