### ISSUE TITLE
please load latest eanthony onto win-3 and fedora20

### ISSUE THREAD

**Issue by ajdamico** [MonetDB/eanthony#56]
https://github.com/MonetDB/eanthony/commit/e60d43b7f2b78ce7870252c0954b17a4c61a5592

https://github.com/MonetDB/eanthony/commit/e60d43b7f2b78ce7870252c0954b17a4c61a5592

**Comment by ajdamico** [comment]
i don't understand how the latest sbo died?  could you re-load the latest?  maybe it didn't take for some odd reason

http://monetdb.cwi.nl/testweb/web/sisyphus/fedora20-3/1465477434/sbo.log

**Comment by ajdamico** [comment]
limit1 also broke with code that's no longer on the live site..  http://monetdb.cwi.nl/testweb/web/sisyphus/fedora20-4/1465489991/limit1.log

**Comment by ajdamico** [comment]
sorry i'm a moron.  apparently the "sync" button was not in my repertoire yesterday.

https://github.com/MonetDB/eanthony/commit/5c960cde5331b9d15b90942c3a979e83e1ec8536

please pull latest to both lab14win and fedora20..thanks

**Comment by ajdamico** [comment]
think this was done

**Comment by ajdamico** [comment]
packages.R needed an update https://github.com/MonetDB/eanthony/commit/4521bdd4b1737bc8c21635997c7fd0c1705e3190

not sure if i should also be able to do this myself with `ssh stones14/15`?

**Comment by hannes** [comment]
you could try doing a git pull in /scratch/hannes/eanthony on stones15

**Comment by hannes** [comment]
updated it tho

**Comment by ajdamico** [comment]
nvss now uses 7zip on unix which fixes at least the current crash
https://github.com/ajdamico/asdfree/issues/125

**Comment by ajdamico** [comment]
@hannesmuehleisen unix nvss won't work until this has been re-uploaded but the windows nvss hanging business is not reproducible for me

```
> dbListTables(dbConnect(MonetDBLite(),dbfolder))
[1] "natality_ps_2011" "natality_us_2011"
```

**Comment by ajdamico** [comment]
i updated r-tag but i believe the `win-3` needs to be upgraded manually

https://cran.r-project.org/bin/windows/base/

https://github.com/MonetDB/eanthony/commit/ceee9c2f3e518673d59bc5af380533e9fb8b819e

**Comment by hannes** [comment]
updated

**Comment by ajdamico** [comment]
please pull latest..  https://github.com/MonetDB/eanthony/commit/2f6702841f257cf67a8c9cf9f433fa3486f135d8

**Comment by ajdamico** [comment]
this too, sorry  https://github.com/MonetDB/eanthony/commit/27873536c2877d393538d1ea5d9c05180bc2a200

**Comment by ajdamico** [comment]
really confused why [the latest arf run](http://homepages.cwi.nl/~hannes/sisyphus/fedora20-4/1467043200/arf.log) is printing what appears to be default merge conflict lines.  they are not in the latest eanthony code

**Comment by hannes** [comment]
they are results of a borked merge

**Comment by ajdamico** [comment]
@hannesmuehleisen how about this addition?  our best shot at a minimal path to a segfault..

https://github.com/MonetDB/eanthony/commit/e1b7abd58a1ff01768999612c5afae2d984e8353

**Comment by hannes** [comment]
done

**Comment by ajdamico** [comment]
@hannesmuehleisen i fixed the problem crashing `convey_devtools` so please reload

i don't understand why arf is still crashing..that merge conflict line isn't anywhere that i see it

`nvss` winrar looks like it's still hanging

for the `ces` bug, do you need some sudo apt-get magic to load `libxml2-dev`?

thanx

**Comment by ajdamico** [comment]
homie you restarted win3 but the latest code also needs a re-pull? thanks

**Comment by ajdamico** [comment]
sorry, please re-load arf on both machines.  [this](https://github.com/MonetDB/eanthony/commit/48f4410bca09d938dee2595f0eb1624c25554785) fixes [this](http://homepages.cwi.nl/~hannes/sisyphus/win-3/1467293227/arf.log)

**Comment by ajdamico** [comment]
i think arf and cran_replacements on both machines need to be pulled..thanks

**Comment by ajdamico** [comment]
dev version of haven no longer necessary  https://github.com/MonetDB/eanthony/commit/6e2c4c252e46ca5392e780540b2a54f6cdf9b59e

pulling the latest onto fedora20 myself with `ssh hannes@stones15` asks me for a pw
