### ISSUE TITLE
rss feed broken

### ISSUE THREAD

**Issue by ajdamico** [MonetDB/eanthony#60]
http://homepages.cwi.nl/~hannes/sisyphus/?rss

**Comment by hannes** [comment]
works for me?

**Comment by ajdamico** [comment]
screenshot..  am i doing something stupid?  thanks

![rss feed output](https://cloud.githubusercontent.com/assets/216807/16435219/5f325f64-3d62-11e6-8591-f869cf2c2d81.png)

**Comment by hannes** [comment]
perhaps it got too big will investigate

**Comment by ajdamico** [comment]
ya did somethin good here too

**Comment by hannes** [comment]
This should work: http://monetdb.cwi.nl/testweb/web/sisyphus/?rss ?

**Comment by hannes** [comment]
confirmed it is broken

**Comment by hannes** [comment]
try again plz

**Comment by ajdamico** [comment]
thanks :)
