### ISSUE TITLE
auto-test RSQLite dependent package example Rd and testthats

### ISSUE THREAD

**Issue by ajdamico** [MonetDB/eanthony#61]
write an eanthony function that downloads a package source

replaces RSQLite with MonetDBLite throughout the text

runs devtools::check and the dontrun blocks

to confirm complete transferability btw the two packages

**Comment by ajdamico** [comment]
thinking a generalized version of [this convey_devtools commit](https://github.com/MonetDB/eanthony/commit/e1b7abd58a1ff01768999612c5afae2d984e8353), but just one test per package and not a bunch.  @hannesmuehleisen thoughts?

**Comment by ajdamico** [comment]
@hannesmuehleisen harder than i thought, but something like this?  https://github.com/MonetDB/eanthony/commit/6d007a889e4e923141ac770af732abe6176f6859

**Comment by hannes** [comment]
curious what it will do
