### ISSUE TITLE
recommended syntax for src_monetdblite

### ISSUE THREAD

**Issue by ajdamico** [MonetDB/eanthony#63]
```
library(DBI)
library(dplyr)

# fails
my_db_monetdb <- src_monetdblite()
```

should aliases for `src_monetdb()` and `src_monetdblite()` be included in `dplyr` next version, or is the recommended syntax one of these?

```
my_db_monetdb <- MonetDBLite::src_monetdblite()
```

or

```
library(MonetDBLite)
my_db_monetdb <- src_monetdblite()
```

thanks

**Comment by hannes** [comment]
`MonetDBLite::src_monetdblite()` is it for MonetDBLite + dplyr

**Comment by ajdamico** [comment]
thx
