### ISSUE TITLE
consider replicating sisyphus for non-MonetDBLite asdfree scripts

### ISSUE THREAD

**Issue by ajdamico** [MonetDB/eanthony#69]
low-priority: if CWI sets up a replacement for rocks040 (not stones15) and if @hannesmuehleisen says its ok to use a lot of computing power on-site, consider setting up other scripts with the same perpetual testing framework

**Comment by hannes** [comment]
rocks will come back and it's fine. will ping you when they are back online

**Comment by ajdamico** [comment]
thanks chief
