### ISSUE TITLE
could we update libcurl on stones15?

### ISSUE THREAD

**Issue by ajdamico** [MonetDB/eanthony#72]
trying to fix the consumer expenditure survey script led me to this solution:

http://stackoverflow.com/a/35064740/1759499

```
[damico@stones15 ~]$ curl-config --version
libcurl 7.32.0
```

it looks like we might need sisyphus to access the latest version of libcurl?  here's the install line, but i think it needs to be run by someone with root?

```
sudo apt-get install libcurl4-openssl-dev
```

here's a minimal reproducible example of the lines that work properly on windows but fail on stones15

```
library(rvest)
cpov <- "https://www.census.gov/data/tables/time-series/demo/income-poverty/historical-poverty-thresholds.html" 
pg <- read_html(cpov)

# stone15 error message:
Error in open.connection(x, "rb") : SSL connect error
```

thanks

**Comment by hannes** [comment]
not really happening the machine will be reinstalled at some point though. the problem is that the version of libcurl that is part of fedora20 is just too old.

**Comment by ajdamico** [comment]
thanks

@ajdamico when this gets resolved, re-try https://github.com/MonetDB/eanthony/issues/67
