### ISSUE TITLE
please install perl on stones14win?

### ISSUE THREAD

**Issue by ajdamico** [MonetDB/eanthony#79]
currently hitting this error..

http://monetdb.cwi.nl/testweb/web/sisyphus/stones14win/1480460685/pums.log

readxl::read_excel() does not work   https://github.com/MonetDB/eanthony/issues/76

openxlsx::read.xlsx() does not read xls files

     http://www2.census.gov/census_2000/datasets/PUMS/FivePercent/5%25_PUMS_record_layout.xls

xlsx::read.xlsx() would work but requires rJava

**Comment by hannes** [comment]
should be installed

**Comment by ajdamico** [comment]
http://monetdb.cwi.nl/testweb/web/sisyphus/stones14win/1480598594/pums.log

**Comment by ajdamico** [comment]
i now should be able to remove reliance on `library(gdata)` and with it perl

https://github.com/ajdamico/lodown/issues/89
