### ISSUE TITLE
please delete cached file on fedora20

### ISSUE THREAD

**Issue by ajdamico** [MonetDB/eanthony#84]
'/export/scratch1/home/hannes/eanthony/r-tmp/pisa/c25683ebd5803f14980be45ef057ebb0.Rdownloadercache'

the point where pisa is breaking worked fine for me locally..

	> fn <- 'http://vs-web-fs-1.oecd.org/pisa/PUF_SAS_COMBINED_CMB_STU_COG.zip'
	> tf <- tempfile()
	> download.file(fn,tf,mode='wb')
	trying URL 'http://vs-web-fs-1.oecd.org/pisa/PUF_SAS_COMBINED_CMB_STU_COG.zip'
	Content type 'application/x-zip-compressed' length 201538239 bytes (192.2 MB)
	downloaded 192.2 MB

	> z <- unzip(tf,exdir=tempdir())
	> z
	[1] "C:/Users/AnthonyD/AppData/Local/Temp/9/RtmpMpKgig/CY6_MS_CMB_STU_COG.sas7bdat"           
	[2] "C:/Users/AnthonyD/AppData/Local/Temp/9/RtmpMpKgig/CY6_MS_CMB_STU_COG.sas7bdat.format.sas"
	> library(haven)
	> w <- read_sas(z[1])

**Comment by hannes** [comment]
it's dead jim

**Comment by ajdamico** [comment]
haha

On Tue, Dec 13, 2016 at 11:55 AM, Hannes Mühleisen <notifications@github.com
